### PR TITLE
Modify python and js

### PR DESCRIPTION
**Pull request by youzhonghui**
Python look like this:

a

JS:

b

### CODE REVIEW

**Comment by schmittyjd** [comment]
I really like the python looks of this. Part of me wants the const keyword to be a different color in js though, it should stand out more imho

**Comment by youzhonghui** [comment]
Yes, you are right. I turn the const into red now.

**Comment by simurai** [comment]
#28 will add conflicts to this PR, but I see there are already conflicts now.

@youzhonghui Sorry for not reviewing earlier. If you don't mind explaining the changes in more detail and the reason for the changes. Also splitting it up into smaller PRs would make it easier to review.

**Comment by simurai** [comment]
Closing as `stale`.

**Pull request closed without merging**
